name: Build wasm

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_wasm:
    name: build wasm
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
      - name: Get Python version
        run: python -V
      - name: Install dependencies
        run: pip install meson ninja
      - name: build wasm
        run: |
          meson setup build --cross-file wasm.ini -Dcpp_std=c++20
          mkdir public
          cp build/examples/rectray_glfw_imgui.* public/
      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: wasm build
          path: public
