name: Build wasm

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_wasm:
    name: build wasm
    runs-on: ubuntu-20.04

    steps:
      - name: Verify python
        run: python3 -V
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: pip install meson ninja
      - name: Verify meson
        run: |
          pwd
          which meson
          find /home/runner/.local -name mesonbuild
      - name: patch meson
        run: patch -u /home/runner/.local/lib/python3.8/site-packages/mesonbuild/compilers/cpp.py < meson.patch
      - uses: mymindstorm/setup-emsdk@v11
      - name: Verify
        run: emcc -v
      - name: build wasm
        run: |
          meson setup build --cross-file wasm.ini -Dcpp_std=c++2b
          meson compile -C build
          mkdir public
          cp build/examples/rectray_glfw_imgui.* public/
      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: wasm build
          path: public
